name: money_reader
description: Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  camera: ^0.8.1+7
  just_audio: ^0.9.37
  sqflite: ^2.3.2

  # path_provider: ^2.0.2
  # flutter_vibrate: ^1.1.0

  intl: ^0.19.0
  light: ^3.0.1
  tflite: ^1.1.2
  google_fonts: ^6.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cash_recognition/audio/nrs_audio/
    - assets/cash_recognition/models/nrs_model/
    - assets/cash_recognition/images/
    - assets/cash_recognition/instructions/
    - assets/